services:
  pyspark-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pyspark_semana10
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
    restart: unless-stopped
